### PR TITLE
Update README_fr.md

### PR DESCRIPTION
**Pull request by madmaxlamenace**
Comment changer d'une version à une autre Team<->Enterprise

## Problem

- *Changer de la version Entreprise à Team et vice et versa*

## Solution

- *En modifiant le fichier settings et en affectuant la mise à jour de l'application*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by kemenaran** [comment]
This looks like something worth to be mentioned in the README, yes.

@ericgaspar are manual edits to the README overwritten by the auto-readme, or is it fine?

**Comment by ericgaspar** [comment]
I guess we need to use the `DISCLAIMER.md` file that will generate the README

**Comment by ericgaspar** [comment]
Changing the Team<->Enterprise setting will be a nice feature to implement with `config_panel`

**Comment by ericgaspar** [comment]
superseded by #317

**Pull request closed without merging**
