### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ericgaspar**
#413

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Review by kemenaran — APPROVED** [review]
I’m not sure we should bump the version number: won’t this trigger an unnecessary upgrade on systems that already migrated the database successfully?

**Comment by ericgaspar** [comment]
I guess the update will be offered even if we don't increment the version number. Alternatively we could merge upgrade to 7.8.1 https://github.com/YunoHost-Apps/mattermost_ynh/pull/412 to testing (armhf team version being stuck to 7.5.2 version...)

**Comment by kemenaran** [comment]
If it triggers an upgrade anyway, let’s fix the small migration issue first.

**Pull request merged**
