### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Review by kemenaran — APPROVED** [review]
Works on my instance 👍 

Although I noticed the pre-upgrade backup is now 10 Go large (!) on my instance. I guess it includes media files (it would properly exclude them before) ; seems like a regression from a previous PR.

Nothing preventing merging this one though - but maybe can you have a look at what broke this?

**Comment by ericgaspar** [comment]
I think this is fix in the core. What YNH version are you running Mattermost on?

**Comment by kemenaran** [comment]
@ericgaspar I'm on yunohost v11.2.30.2.

**Pull request merged**
