### PR TITLE
Propose Upgrading to Mattermost v5.22.3

### PR DESCRIPTION
**Pull request by amyblais**
Hi @kemenaran!

Mattermost v5.22.3 dot release is officially out.

You can find download links with hash numbers [here](https://community.mattermost.com/core/pl/kx3yrgpqa7d49fnim6izzitwge). Changelog with notes on patch releases is available [here](https://docs.mattermost.com/administration/changelog.html).

Thanks!

### CODE REVIEW

**Comment by amyblais** [comment]
Updated to reflect v5.22.2 dot release

**Comment by amyblais** [comment]
Updated to reflect v5.22.3 dot release

**Comment by ericgaspar** [comment]
> Updated to reflect v5.22.3 dot release

version number should also be reflected in `manifest.json` ligne 11

`    "version": "5.22.3~ynh1",`

so that YunoHost knows it is dealing with a new version and triggers the upgade script

**Comment by kemenaran** [comment]
@ericgaspar thanks for remining me to update the Yunohost version number!

@amyblais to be able to merge this PR, I changed the version number manually in the manifest (see the [relevant changes](https://github.com/YunoHost-Apps/mattermost_ynh/pull/170/files)). Probably this will have to be done for each Mattermost release submitted.

**Pull request merged**
