### PR TITLE
Update VERSION

### PR DESCRIPTION
**Pull request by lindy65**
Hi @kemenaran,

Mattermost v4.3.1 dot release is officially out.  

You can [find download links with hash numbers here](https://pre-release.mattermost.com/core/pl/1m4s4q1q97fezgzuuod4ag8tah).  Changelog with notes on patch releases will be available [here](https://docs.mattermost.com/administration/changelog.html#mattermost-changelog) later today.

Thanks!

### CODE REVIEW

**Comment by kemenaran** [comment]
@lindy65 thanks for the PR! That said I still can't find the changelog for this 4.3.1 version. I tried to follow the link you provided (thanks for this!), but the changes only go up to version 4.3.0. Is it available somewhere?

**Comment by lindy65** [comment]
Hi @kemenaran,

The v4.3.1 Changelog should be ready a little later today and I'll send you the link here once it's done.  Apologies for the delay!

**Comment by lindy65** [comment]
Hi @kemenaran,

Here is the link to the [changelog](https://docs.mattermost.com/administration/changelog.html#release-v4-3-1) and the correct download links [here](https://pre-release.mattermost.com/core/pl/jtshyqakrbga8cqiucx6pci47c) - the earlier links I provided were for the RC - so sorry about the mix-up and disorganisation this time around :(

**Comment by kemenaran** [comment]
@lindy65 thanks for the heads-up! I've read the changelog, and it all looks correct now.

That said, the format for declaring the Mattermost version recently changed :/ The `VERSION` file  doesn't exist anymore. It has been replaced by the [conf/app.src](https://github.com/YunoHost-Apps/mattermost_ynh/blob/master/conf/app.src) file.

To bump Mattermost to a new version, this file needs to be edited with:

- The download link to the new version compiled binary ;
- The SHA256 checksum.

All these informations can be found on the [Mattermost Version Archive](https://docs.mattermost.com/administration/version-archive.html#version-archive) page.

Do you want to try this new update – or do you prefer that I do it myself for the first time with this new process?

**Comment by lindy65** [comment]
Hi @kemenaran,

Thanks for the update on the new process...

I'd appreciate if you could do the update with the new process this time :)

I will try it for next release!

**Comment by kemenaran** [comment]
Closed in favor of #71

**Pull request closed without merging**
