### PR TITLE
Use the refactored scripts

### LINKED ISSUE #87: [quality] Follow more Yunohost quality recommandations
See https://yunohost.org/#/packaging_apps_guidelines_en

### PR DESCRIPTION
**Pull request by alexAubin**
Followup of https://github.com/YunoHost-Apps/mattermost_ynh/pull/203

Fix #87, #108, #124, #204, #207

### CODE REVIEW

**Comment by alexAubin** [comment]
!testme

**Comment by kemenaran** [comment]
I posted a [request for tests](https://forum.yunohost.org/t/request-test-the-new-mattermost-package/14243) on the Yunohost forum. Once a handfull of people can confirm it's working in various situations, let's merge this!

**Comment by farvardin** [comment]
I've seen how to install mattermost from testing. But I want to restore a mattermost backup (our mattermost is down for a couple of weeks), and I don't know how I could do that. Your message on forum implies it should be possible.

**Comment by alexAubin** [comment]
Not sure what you mean @farvardin ... if you have a backup, why not restore it using the usual backup restore workflow of yunohost ...?

**Comment by farvardin** [comment]
@alexAubin Because the mattermost package in master is broken: I've tried to install or restore mattermost and it's not working: cf. https://github.com/YunoHost-Apps/mattermost_ynh/issues/204

> YunohostError: Échec de l’exécution du script : /tmp/restore027Nd6/restore

**Comment by alexAubin** [comment]
Mokay but: 
- the post you mention contain a failed installed log, which yes, should indeed be fixed by this branch
- dunno about the restore but can't debug it without the corresponding log ...

Ideally we should discuss "how to fix/workaround the broken restore of the old version" in the corresponding issue ...

**Comment by farvardin** [comment]
on https://forum.yunohost.org/t/request-test-the-new-mattermost-package/14243 @kemenaran wrote:

> Restoring a backup made on master using the testing branch

it's the reason why I'm asking on this thread how to do this. I have the backup made on master, and I want to try to restore it on the testing branch

**Comment by alexAubin** [comment]
Wokay, not sure what kemenaran but you can't "restore a backup made on master using the testing branch" ... you could imagine tweaking the archive to inject the new restore script if the old restore script is broken, but that's assuming that's the cause of the issue is the restore script, and not something else ...

**Comment by farvardin** [comment]
I was wondering if there was a secret command to handle this, but then I'll wait until it is merged into master...

**Comment by alexAubin** [comment]
Sorry to not be clear enough but **this PR doesn't matter for your backup/restore issue**. The restore happens **using the restore script and other stuff contained in the archive**. Even if we merge this it has **no impact on your restore issue**...

**Comment by farvardin** [comment]
ok, thank you for the clarification. I didn't know the restore was independant from the main package. I'll try to handle the problem by hand then.

**Comment by kemenaran** [comment]
@farvardin yep, sorry about this: I was also confused, and though the restore script used the most recent version (and not the packaged version).

**Comment by kay0u** [comment]
> @farvardin yep, sorry about this: I was also confused, and though the restore script used the most recent version (and not the packaged version).

No, the restore script used during a restore process is the one that existed at the time of the backup.

**Comment by alexAubin** [comment]
Sooooooo idk, are we good to go ...?

**Comment by kemenaran** [comment]
I'd say "let's merge it": the current version is broken on some recent Yunohost installations anyway.

**Pull request merged**
