### PR TITLE
Upgrade to Matermost 5.39.0

### PR DESCRIPTION
**Pull request by kemenaran**
CHangelog : https://docs.mattermost.com/install/self-managed-changelog.html#release-v5-39-quality-release

### CODE REVIEW

**Comment by kemenaran** [comment]
!testme

**Comment by tituspijean** [comment]
⚠️ Somehow the checksums for ARM and ARM64 do not match anymore.
(discovered while comparing with #277 outputs)

**Comment by ericgaspar** [comment]
@tituspijean you mean because of the update script using sha256sum instead of sha512sum used in this PR?

**Comment by tituspijean** [comment]
@ericgaspar Ooops my bad, indeed I did not notice the kind of checksum being used.

**Comment by ericgaspar** [comment]
@kemenaran Maybe we can switch back to sha256sum instead of sha512sum for the two GitHub repos?

**Comment by kemenaran** [comment]
The reason third-party builds use a sha512 for now is that the [digests are published along with the releases](https://github.com/SmartHoneybee/ubiquitous-memory/releases) – so there's no need to download the whole release to re-compute the digest locally.

(But if that bothers maintainers, we can go the "download everything" route anyway, it doesn't matter very much)

**Comment by ericgaspar** [comment]
With the auto-update mechanism, shasums are generated automatically but we need to homogenize all the shasums to 256.

**Comment by tituspijean** [comment]
Checksums could be variable. It is a nice thing that upstream publishes the checksums themselves, so that we have another means of verifying the sources are not altered. It's up to you guys, I can come up with an alteration of the update script.

**Comment by kemenaran** [comment]
@ericgaspar is this fine with you?

**Review by ericgaspar — APPROVED** [review]

**Pull request merged**
