### PR TITLE
upgrade to 7.8.1

### LINKED ISSUE #404: Propose upgrading to Mattermost v7.7.1
Hi @kemenaran,

Mattermost v7.7.1 release is officially out.

You can find download links with hash numbers [here](https://community.mattermost.com/core/pl/suqjjkeertd3pfm7gczujzcq3a). Changelog with notes on patch releases is available [here](https://docs.mattermost.com/administration/changelog.html).

Thanks!

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

Fix #404

### CODE REVIEW

**Comment by ericgaspar** [comment]
we are missing the `team_armhf.src` update for `7.7.1`...

**Comment by ericgaspar** [comment]
!testme

**Comment by kay0u** [comment]
!testme

**Review by kemenaran — APPROVED** [review]
LGTM

If I understand correctly, the armhf version is not available. How will the upgrade fail on these systems? Is there a relatively descriptive error for the user?

**Pull request merged**
