### PR TITLE
Merge testing into master

### PR DESCRIPTION
**Pull request by ericgaspar**
- Systemd Hardening
- Set rights
- Matermost 5.39.0

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Review by alexAubin — APPROVED** [review]
:+1:

**Comment by ericgaspar** [comment]
!testme

**Comment by kemenaran** [comment]
That looks fine to me. I'm a bit concerned by the backup/restore not working (like in #287), but there's no strong reason not to release this one now ; we can fix the restore in another release.

**Pull request merged**
