### PR TITLE
Update systemd configuration to fix preview links

### LINKED ISSUE #340: Preview links broken ?
### Describe the bug

*A clear and concise description of what the bug is.*

### Context

- Hardware: *VPS bought online*
- YunoHost version: 4.3.6.2
- I have access to my server: *Through SSH *
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using package version/branch: 6.3.3~ynh1*

### Steps to reproduce

Post a link in a channel. Result is just a plain https link.

### Expected behavior

A preview of the Youtube link with header and description

in my config.json
```
{
    "ServiceSettings": {
        "SiteURL": "https://mydomain.tld",
        "WebsocketURL": "",
        "LicenseFileLocation": "",
        "ListenAddress": "127.0.0.1:8065",
        "ConnectionSecurity": "",
        "TLSCertFile": "",
        "TLSKeyFile": "",
        "TLSMinVer": "1.2",
        "TLSStrictTransport": false,
        "TLSStrictTransportMaxAge": 63072000,
        "TLSOverwriteCiphers": [],
        "UseLetsEncrypt": false,
        "LetsEncryptCertificateCacheFile": "./config/letsencrypt.cache",
        "Forward80To443": false,
        "TrustedProxyIPHeader": [],
        "ReadTimeout": 300,
        "WriteTimeout": 300,
        "IdleTimeout": 60,
        "MaximumLoginAttempts": 10,
        "GoroutineHealthThreshold": -1,
        "EnableOAuthServiceProvider": false,
        "EnableIncomingWebhooks": true,
        "EnableOutgoingWebhooks": true,
        "EnableCommands": true,
        "EnablePostUsernameOverride": false,
        "EnablePostIconOverride": false,
        "GoogleDeveloperKey": "",
        "EnableLinkPreviews": true,
        "EnablePermalinkPreviews": true,
        "RestrictLinkPreviews": "",
        "EnableTesting": false,
        "EnableDeveloper": false,
        "DeveloperFlags": "",
        "EnableOpenTracing": false,
        "EnableSecurityFixAlert": true,
        "EnableInsecureOutgoingConnections": false,
        "AllowedUntrustedInternalConnections": "",
        "EnableMultifactorAuthentication": false,
        "EnforceMultifactorAuthentication": false,
        "EnableUserAccessTokens": false,
        "AllowCorsFrom": "",
        "CorsExposedHeaders": "",
        "CorsAllowCredentials": false,
        "CorsDebug": false,
        "AllowCookiesForSubdomains": false,
        "ExtendSessionLengthWithActivity": true,
        "SessionLengthWebInDays": 30,
        "SessionLengthMobileInDays": 30,
        "SessionLengthSSOInDays": 30,
        "SessionCacheInMinutes": 10,
        "SessionIdleTimeoutInMinutes": 43200,
        "WebsocketSecurePort": 443,
        "WebsocketPort": 80,
        "WebserverMode": "gzip",
        "EnableGifPicker": false,
        "GfycatAPIKey": "2_O23cJw",
        "GfycatAPISecret": "lhoh6S94nBNdnVvqieFx1coaIMiGJPLhhs5HCxEt830Dg88bbCczmbiewh07fQ0g",
        "EnableCustomEmoji": true,
        "EnableEmojiPicker": true,
        "PostEditTimeLimit": -1,
        "TimeBetweenUserTypingUpdatesMilliseconds": 5000,
        "EnablePostSearch": true,
        "EnableFileSearch": true,
        "MinimumHashtagLength": 3,
        "EnableUserTypingMessages": true,
        "EnableChannelViewedMessages": true,
        "EnableUserStatuses": true,
        "ExperimentalEnableAuthenticationTransfer": true,
        "ClusterLogTimeoutMilliseconds": 2000,
        "EnablePreviewFeatures": true,
        "EnableTutorial": true,
        "EnableOnboardingFlow": true,
        "ExperimentalEnableDefaultChannelLeaveJoinMessages": true,
        "ExperimentalGroupUnreadChannels": "disabled",
        "EnableAPITeamDeletion": false,
        "EnableAPIUserDeletion": false,
        "ExperimentalEnableHardenedMode": false,
        "ExperimentalStrictCSRFEnforcement": false,
        "EnableEmailInvitations": true,
        "DisableBotsWhenOwnerIsDeactivated": true,
        "EnableBotAccountCreation": false,
        "EnableSVGs": false,
        "EnableLatex": false,
        "EnableInlineLatex": true,
        "EnableAPIChannelDeletion": false,
        "EnableLocalMode": false,
        "LocalModeSocketLocation": "/var/run/mattermost/mattermost_local.socket",
        "EnableAWSMetering": false,
        "SplitKey": "",
        "FeatureFlagSyncIntervalSeconds": 30,
        "DebugSplit": false,
        "ThreadAutoFollow": true,
        "CollapsedThreads": "disabled",
        "ManagedResourcePaths": ""
    },
```
the port 8065 is open in the firewall...

### PR DESCRIPTION
**Pull request by kemenaran**
Currently the links preview attached to a post containing URLs in broken.

This is because the current systemd hardening prevents the Go networking library from resolving a hostname to an IP.

Adding the correct permission fixes the hostname resolution, which fixes the retrieval of link previews by Mattermost's server.

Fix #340

### CODE REVIEW

**Comment by kemenaran** [comment]
By the power of systemd, I invoke The Great App CI to test this Pull Request!

**Comment by ericgaspar** [comment]
tested and working 👍

**Comment by isAAAc** [comment]
ohhh cool !
i opened some issue(s) about this point of preview are KO since months ago, 
i wish it'lll fix it :crossed_fingers:

**Comment by isAAAc** [comment]
yes fixed <3

**Pull request merged**
