### PR TITLE
tool: add a script for maintainers to bump the Mattermost version

### PR DESCRIPTION
**Pull request by kemenaran**
This script is supposed to be run by maintainers locally, and will edit the `conf/src` and `README` files with the new version.

Future steps: integrating this script in an automated action that would create the Github PR.

### CODE REVIEW

**Comment by kemenaran** [comment]
This script has generated the releases for a few versions now; I'm merging it.

For now it has to be run manually by a maintainer, but later it may be integrated as a Github Action.

**Comment by kemenaran** [comment]
@amyblais know if do you there's a way to retrieve the hash numbers of a release programatically? For instance an URL like `https://releases.mattermost.com/<version>/mattermost-<edition>-<version>-linux-amd64.sha256`, that would provide the sha256 of the given release?

**Comment by amyblais** [comment]
> @amyblais know if do you there's a way to retrieve the hash numbers of a release programatically? For instance an URL like `https://releases.mattermost.com/<version>/mattermost-<edition>-<version>-linux-amd64.sha256`, that would provide the sha256 of the given release?

I'm not sure, @cpanato do you know?

**Comment by cpanato** [comment]
we don't have this at the moment, but that we can push as well

@amyblais can you make a ticket and assign that to me? also mention this issue then we can ping back here once is implemented

**Comment by kemenaran** [comment]
@cpanato that'd be great! For the context, I'm writing a script to auto-generate the version file for new Mattermost releases, including the hash number.

For now my current workaroud is to download the entire Team and Enterprise releases, and hash them locally – but that takes some time and bandwidth :)

**Comment by ericgaspar** [comment]
READMEs are generated automatically now -> #248

**Comment by cpanato** [comment]
> @cpanato that'd be great! For the context, I'm writing a script to auto-generate the version file for new Mattermost releases, including the hash number.
> 
> For now my current workaround is to download the entire Team and Enterprise releases, and hash them locally – but that takes some time and bandwidth :)

we are publishing the SHA in the release bucket

**Comment by kemenaran** [comment]
@cpanato thanks, that's great :)

Do you know how to access the SHA? I tried for instance https://releases.mattermost.com/5.39.0/mattermost-5.39.0-linux-amd64.tar.gz.sha256, but it doesn't seem to work.

**Comment by cpanato** [comment]
this will be available for releases > 6.0
sorry forgot to mention that

**Pull request merged**
